app/urls.py
from django.urls import path
from app.views import (
    index,
    RegisterView,
    LoginView,
    LogoutView,
    VoteView, CancelVote, themePage, CreatePoll, UserProfile, EditProfile)

urlpatterns = [
    path('', index, name='home'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('poll/<int:pk>/vote/<int:rez>', VoteView.as_view(), name='vote'),
    path('poll/<int:pk>/vote/cancel', CancelVote.as_view(), name='cancelVote'),
    path('theme/<int:theme_key>', themePage, name='themePage'),
    path('createpoll', CreatePoll.as_view(), name='createPoll'),
    path('userprofile/<int:pk>', UserProfile.as_view(), name='userProfile'),
    path('editprofile/<int:pk>', EditProfile.as_view(), name='editProfile'),
]

we_say/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Theme(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Poll(models.Model):
    question = models.CharField(max_length=100)
    text = models.CharField(max_length=2000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    created_by = models.ForeignKey(User, related_name='polls', on_delete=models.CASCADE)
    theme = models.ForeignKey(Theme, related_name='polls', on_delete=models.CASCADE)

    @property
    def getResults(self):
        totalVotes = self.votes.all().count()

        if totalVotes > 0:
            numberYes = self.votes.filter(option=True).count()
            numberNo = self.votes.filter(option=False).count()

            percentageYes = 100 * numberYes / totalVotes
            percentageNo = 100 * numberNo / totalVotes

            return "Rezultate: {}% DA, {}% NU (Total: {} voturi)".format(percentageYes, percentageNo, totalVotes)

        else:
            return "Încă nu a votat nimeni!"

class Vote(models.Model):
    option = models.BooleanField()
    poll = models.ForeignKey(Poll, related_name='votes', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='votes', on_delete=models.CASCADE)

app/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, TemplateView, UpdateView

from app.models import User, Poll, Vote, Theme


def index(request):
    if request.GET.get('sort') == '1':
        posts = Poll.objects.all().order_by("-created_at")[:10]
    elif request.GET.get('sort') == '2':
        posts = Poll.objects.all().annotate(num_voters=Count('votes')).order_by('-num_voters')[:10]
    else:
        posts = Poll.objects.all().order_by("-created_at")[:10]

    return render(request, 'home.html', context={'polls':posts})

def themePage(request, theme_key):
    if request.GET.get('sort') == '1':
        posts = Poll.objects.filter(theme_id=theme_key).order_by("-created_at")[:10]
    elif request.GET.get('sort') == '2':
        posts = Poll.objects.filter(theme_id=theme_key).annotate(num_voters=Count('votes')).order_by('-num_voters')[:10]
    else:
        posts = Poll.objects.filter(theme_id=theme_key).order_by("-created_at")[:10]

    return render(request, 'home.html', context={'polls':posts})

class RegisterView(CreateView):
    template_name = 'register.html'
    form_class = UserCreationForm
    model = User

    def form_valid(self, form):
        data = form.cleaned_data
        user = User.objects.create_user(username=data['username'],
                                        password=data['password1'])
        return redirect('home')


class LoginView(TemplateView):
    template_name = 'login.html'

    def get_context_data(self):
        form = AuthenticationForm()
        return {'form': form}

    def post(self, request, *args, **kwargs):
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(username=data['username'],
                                password=data['password'])
            login(request, user)
            return redirect(reverse_lazy('home'))
        else:
            return render(request, "login.html", {"form": form})


class LogoutView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect(reverse_lazy('home'))

class VoteView(View):
    def get(self, request, *args, **kwargs):
        vote = Vote.objects.filter(poll_id=kwargs['pk'], user=request.user).first()
        if not vote:
            vote = Vote.objects.create(poll_id=kwargs['pk'], option=kwargs['rez'], user=request.user)
        else:
            vote.option=kwargs['rez']
            vote.save()
        # return redirect(reverse_lazy('home'))
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

class CancelVote(View):
    def get(self, request, *args, **kwargs):
        vote = Vote.objects.filter(poll_id=kwargs['pk'], user=request.user).first()
        if vote:
            vote.delete()
        # return redirect(reverse_lazy('home'))
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

class CreatePoll(CreateView):
    model = Poll
    fields = ['question', 'text', 'theme']
    template_name = 'createpoll.html'

    def form_valid(self, form):
        Poll.objects.create(
            created_by=self.request.user,
            **form.cleaned_data
        )
        return redirect(reverse_lazy('home'))

class UserProfile(View):
    def get(self, request, *args, **kwargs):
        user_profile = User.objects.filter(id=kwargs['pk']).first()

        return render(request, 'userprofile.html', context={'user_profile':user_profile})

class EditProfile(UpdateView):
    model = User
    fields = ['first_name', 'last_name', 'email']
    template_name = 'editprofile.html'

    def form_valid(self, form):
        self.object.first_name = form.cleaned_data['first_name']
        self.object.last_name = form.cleaned_data['last_name']
        self.object.email = form.cleaned_data['email']

        self.object.save()

        return redirect(reverse_lazy('userProfile', kwargs={'pk':self.object.id}))

app/templates/base.html
{% load static %}
<html>
  <head>
    <title>
      {% block title %}
      {% endblock %}
    </title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <script
          src="https://code.jquery.com/jquery-3.4.1.min.js"
          integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
          crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>




  </head>
  <body>
    {% include 'nav.html' %}

    {% block content %}
    {% endblock %}

    <p>©Cristian Hilohi 2020</p>
  </body>
    {% block js %}
    {% endblock %}
</html>

app/templates/createpoll.html
{% extends 'base.html' %}
{% block title %}
  Create poll
{% endblock%}

{% block content %}
  <div class="container">
      <form method="post" class="justify-content-center" enctype="multipart/form-data">
        {% csrf_token %}
            <div class="form-group">
              <label for="id_question">Intrebarea (maxim 100 de caractere)</label>
              <input type="text" name="question" class="form-control" maxlength="100" required="" id="id_question">
            </div>

            <div class="form-group">
              <label for="id_text">O scurta descriere (maxim 2000 de caractere)</label>
              <textarea class="form-control" rows="3" type="text" name="text" maxlength="2000" required="" id="id_text">
              </textarea>
            </div>

           <div class="form-group">
            <select class="custom-select" name="theme" required="" id="id_theme">
              {% for theme in themes%}
                <option value="{{theme.id}}">{{theme.name}}</option>
              {% endfor %}
            </select>
           </div>

           <input class="btn btn-success" type="submit"  value="Create poll" />
      </form>
  </div>
{% endblock %}

app/templates/editprofile.html
{% extends 'base.html' %}

{% block content %}
<div class="card text-center" style="max-width: 80rem; margin:0 auto; margin-bottom: 3rem">
    <div class="card-header" style="background-color: #FFE4B5">
        Modifica datele profilului
    </div>

    <div class="card-body">
        <form method="post" class="justify-content-center" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <input class="btn btn-success" type="submit"  value="Submit" />
        </form>
    </div>
</div>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}
{% load extras %}
{% block content %}
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Sortare după:
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="?sort=1">data</a>
            <a class="dropdown-item" href="?sort=2">voturi</a>
        </div>
    </div>

    <div class="polls_area">
        {%for poll in polls %}
        <div id="poll_{{poll.id}}" class="card text-center" style="max-width: 80rem; margin:0 auto; margin-bottom: 3rem">
            <div class="card-header" style="background-color: #E0FFFF">
                {{poll.question}}
            </div>
            <div class="card-body">
                <p>
                    {{poll.text}}
                </p>

            {% if user.is_authenticated %}
                {% if user|get_vote_value:poll == 0 %}
                    <div class="alert alert-success" style="max-width: 15rem;  margin:0 auto;">
                        Mulțumim pentru vot!
                        <a class="btn btn-warning" href="{% url 'cancelVote' poll.pk %}">
                            Anulează votul
                        </a>
                        <p>Schimbă votul: </p>
                        <a class="btn btn-success" href="{% url 'vote' poll.pk 1 %}">
                        DA
                        </a>
                    </div>
                {% elif user|get_vote_value:poll == 1 %}
                    <div class="alert alert-success" style="max-width: 15rem;  margin:0 auto;">
                        Mulțumim pentru vot!
                        <a class="btn btn-warning" href="{% url 'cancelVote' poll.pk %}">
                            Anulează votul
                        </a>
                        <p>Schimbă votul: </p>
                        <a class="btn btn-danger" href="{% url 'vote' poll.pk 0 %}">
                        NU
                        </a>
                    </div>
                {% else %}
                    <a class="btn btn-success" href="{% url 'vote' poll.pk 1 %}">
                        DA
                    </a>

                    <a class="btn btn-danger" href="{% url 'vote' poll.pk 0 %}">
                        NU
                    </a>
                {% endif %}

            {% endif %}
            </div>

            <div class="card-footer">
            {{poll.getResults}}
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block content %}
  <h2>Login</h2>
  <form method="post" class="col-6">
    {% csrf_token %}
    <div class="form-group">
        {{ form.errors }}
    </div>

    <div class="form-group">
      <label for="id_username">Username:</label>
      <input type="text" name="username" class="form-control" autofocus="" required="" id="id_username" maxlength="150">
    </div>

    <div class="form-group">
      <label for="id_password">Password:</label>
      <input type="password" name="password" class="form-control" required="" id="id_password">
    </div>

    <button class="btn btn-primary" type="submit">Login</button>
  </form>
{% endblock %}

app/templates/nav.html
<ul class="nav">
  {% if user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'userProfile' user.id %}">Hello, {{ user.username }}</a>
    </li>
    {% if user.is_superuser %}
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'admin:index' %}">Admin</a>
    </li>
    {% endif %}
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'logout' %}">Logout</a>
    </li>
  {% else %}
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'login' %}">Login</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'register' %}">Register</a>
    </li>
  {% endif %}
    <br>

    <br>
    <li href="home" class="nav-item">
        <a class="nav-link active" href="{% url 'home' %}">Home</a>
    </li>
    {% for theme in themes %}
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'themePage' theme.id %}">{{theme.name}}</a>
    </li>
    {% endfor %}

    {% if user.is_authenticated %}
    <li>
         <a class="nav-link active" href="{% url 'createPoll' %}">Create a poll</a>
    </li>
    {% endif %}
</ul>

app/templates/register.html
{% extends 'base.html' %}

{% block content %}
  <h2>Register</h2>
  <form method="post" class="col-6">
    {% csrf_token %}
    <div class="form-group">
        {{ form.errors }}
    </div>

    <div class="form-group">
      <label for="id_username">Username:</label>
      <input type="text" name="username" class="form-control" autofocus="" required="" id="id_username" maxlength="150">
    </div>

    <div class="form-group">
      <label for="id_password1">Password:</label>
      <input type="password" name="password1" class="form-control" required="" id="id_password1">
    </div>

    <div class="form-group">
      <label for="id_password2">Password confirmation:</label>
      <input type="password" name="password2" class="form-control" required="" id="id_password2">
    </div>

    <button class="btn btn-primary" type="submit">Register</button>
  </form>
{% endblock %}

app/templates/themepage.html
{% extends 'base.html' %}

app/templates/userprofile.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h1>Esti autentificat ca {{user.username}}</h1>

    <div class="card text-center" style="max-width: 80rem; margin:0 auto; margin-bottom: 3rem">
        <div class="card-header" style="background-color: #FFE4B5">
            Poll-urile tale
        </div>

        <div class="card-body">
            {% for poll in user.polls.all %}
            <h5><a href="{% url 'home' %}#poll_{{poll.id}}"> {{poll.question}} </a></h5>
            {% endfor %}
        </div>
    </div>

    <div class="card text-center" style="max-width: 80rem; margin:0 auto; margin-bottom: 3rem">
        <div class="card-header" style="background-color: #98FB98">
            Raspunsurile tale
        </div>
            {% for vote in user.votes.all %}
            <div>
                <h5>{{vote.poll.question}} :</h5>
                <h4>
                    {% if vote.option %}
                        DA
                    {% else %}
                        NU
                    {% endif %}
                </h4>
            </div>
            {% endfor %}
        <div class="card-body">

        </div>
    </div>

    <div class="card text-center" style="max-width: 80rem; margin:0 auto; margin-bottom: 3rem">
        <div class="card-header" style="background-color: #FFA500">
            Datele profilului
        </div>

        <div class="card-body">
            <h5>Nume: </h5>
            <p>{{user.first_name}}</p>

            <h5>Nume: </h5>
            <p>{{user.last_name}}</p>

            <h5>Email: </h5>
            <p>{{user.email}}</p>

            <a class="btn btn-primary" href="{% url 'editProfile' user.id %}">Editează datele</a>

        </div>
    </div>
</div>
{% endblock %}